/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { AntisnipeMock, AntisnipeMockInterface } from "../AntisnipeMock";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "assureCanTransfer",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "lastAmount",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastFrom",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "lastTo",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506101b8806100206000396000f3fe608060405234801561001057600080fd5b50600436106100575760003560e01c8063256fec881461005c5780635d37a8dd1461008c57806380443378146100de578063829a86d9146100f1578063c146844714610108575b600080fd5b60005461006f906001600160a01b031681565b6040516001600160a01b0390911681526020015b60405180910390f35b6100dc61009a366004610137565b600080546001600160a01b03199081166001600160a01b0396871617909155600180548216948616949094179093556002805490931691909316179055600355565b005b60015461006f906001600160a01b031681565b6100fa60035481565b604051908152602001610083565b60025461006f906001600160a01b031681565b80356001600160a01b038116811461013257600080fd5b919050565b6000806000806080858703121561014d57600080fd5b6101568561011b565b93506101646020860161011b565b92506101726040860161011b565b939692955092936060013592505056fea26469706673582212206a0ff68e3c767ec6d77b0a2f2a68d8f54c13bb37598dd7d4dd6d972b525b5b2f64736f6c63430008110033";

export class AntisnipeMock__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<AntisnipeMock> {
    return super.deploy(overrides || {}) as Promise<AntisnipeMock>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): AntisnipeMock {
    return super.attach(address) as AntisnipeMock;
  }
  connect(signer: Signer): AntisnipeMock__factory {
    return super.connect(signer) as AntisnipeMock__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): AntisnipeMockInterface {
    return new utils.Interface(_abi) as AntisnipeMockInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): AntisnipeMock {
    return new Contract(address, _abi, signerOrProvider) as AntisnipeMock;
  }
}
